version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vuecmf-php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"

  web:
    image: nginx:alpine
    container_name: vuecmf-nginx-server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

